var GuiYang=[
			 {'cid':17,'county':'云岩区'},
			 {'cid':18,'county':'南明区'},
			 {'cid':19,'county':'花溪区'},
			 {'cid':20,'county':'乌当区'},
			 {'cid':21,'county':'白云区'},
			 {'cid':22,'county':'小河区'},
			 {'cid':23,'county':'清镇市'},
			 {'cid':24,'county':'修文县'},
			 {'cid':25,'county':'息烽县'}
			 ]
var ZunYi=[
			 {'cid':27,'county':'红花岗区'},
			 {'cid':28,'county':'汇川区'},
			 {'cid':29,'county':'赤水市'},
			 {'cid':30,'county':'遵义县'},
			 {'cid':31,'county':'仁怀市'},
			 {'cid':32,'county':'绥阳县'},
			 {'cid':33,'county':'桐梓县'},
			 {'cid':34,'county':'习水县'},
			 {'cid':35,'county':'湄潭县'},
			 {'cid':36,'county':'凤冈县'},
			 {'cid':37,'county':'余庆县'},
			 {'cid':38,'county':'正安县'},
			 {'cid':39,'county':'务川县'},
			 {'cid':40,'county':'道真县'}
			 ]
var AnShun=[
			 {'cid':41,'county':'西秀区'},
			 {'cid':42,'county':'平坝县'},
			 {'cid':43,'county':'普定县'},
			 {'cid':44,'county':'关岭县'},
			 {'cid':45,'county':'镇宁县'},
			 {'cid':46,'county':'紫云县'}
			 ]
var LiuPanShui=[
			 {'cid':47,'county':'钟山区'},
			 {'cid':48,'county':'水城县'},
			 {'cid':49,'county':'六枝特区'},
			 {'cid':50,'county':'盘县特区'}
			 ]
var BiJie=[
			 {'cid':51,'county':'毕节市'},
			 {'cid':52,'county':'赫章县'},
			 {'cid':53,'county':'纳雍县'},
			 {'cid':54,'county':'黔西县'},
			 {'cid':55,'county':'大方县'},
			 {'cid':56,'county':'织金县'},
			 {'cid':57,'county':'金沙县'},
			 {'cid':58,'county':'威宁县'}
			 ]
var TongRen=[
			 {'cid':59,'county':'铜仁市'},
			 {'cid':60,'county':'思南县'},
			 {'cid':61,'county':'江口县'},
			 {'cid':62,'county':'石阡县'},
			 {'cid':63,'county':'德江县'},
			 {'cid':64,'county':'万山特区'},
			 {'cid':65,'county':'印江县'},
			 {'cid':66,'county':'沿河县'},
			 {'cid':67,'county':'玉屏县'},
			 {'cid':68,'county':'松桃县'}
			 ]
var QianNan=[
			 {'cid':84,'county':'都匀市'},
			 {'cid':85,'county':'龙里县'},
			 {'cid':86,'county':'贵定县'},
			 {'cid':87,'county':'福泉市'},
			 {'cid':88,'county':'瓮安县'},
			 {'cid':89,'county':'独山县'},
			 {'cid':90,'county':'平塘县'},
			 {'cid':91,'county':'荔波县'},
			 {'cid':92,'county':'惠水县'},
			 {'cid':93,'county':'长顺县'},
			 {'cid':94,'county':'罗甸县'},
			 {'cid':95,'county':'三都县'}
			 ]
var QianXi=[
			 {'cid':96,'county':'兴义市'},
			 {'cid':97,'county':'兴仁县'},
			 {'cid':98,'county':'晴隆县'},
			 {'cid':99,'county':'普安县'},
			 {'cid':100,'county':'册亨县'},
			 {'cid':101,'county':'望谟县'},
			 {'cid':102,'county':'安龙县'},
			 {'cid':103,'county':'贞丰县'}
			 ]
var QianDong=[
			 {'cid':5,'county':'凯里市'},
			 {'cid':69,'county':'麻江县'},
			 {'cid':70,'county':'黄平县'},
			 {'cid':71,'county':'施秉县'},
			 {'cid':72,'county':'三穗县'},
			 {'cid':73,'county':'天柱县'},
			 {'cid':74,'county':'锦屏县'},
			 {'cid':75,'county':'黎平县'},
			 {'cid':76,'county':'从江县'},
			 {'cid':77,'county':'榕江县'},
			 {'cid':78,'county':'丹寨县'},
			 {'cid':79,'county':'岑巩县'},
			 {'cid':80,'county':'雷山县'},
			 {'cid':81,'county':'台江县'},
			 {'cid':82,'county':'剑河县'},
			 {'cid':83,'county':'镇远县'}
			 ]